-- create hbtn_0d_usa database and table cities(in hbtn_0d_usa)
-- cities
--	id INT unique, autogenerated, can't be null and is a primary key
--	state_id INT can't be null must be a foreign key that references
--		id of state
-- 	name VARCHAR(256) CAN't BE NULL
--
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities(
	id INT PRIMARY KEY  NOT NULL AUTO_INCREMENT,
	state_id INT NOT NULL, FOREIGN KEY(state_id) 
		REFERENCES hbtn_0d_usa.states(id),
	name VARCHAR(256));
